BEHAVE_INI = """[behave]
paths = features
show_skipped = false
show_timings = true
"""

ENVIRONMENT_PY = '''"""Behave hooks — extend for browser/API setup before scenarios run."""

def before_all(context):
    context.test_data = {}


def before_scenario(context, scenario):
    context.current_page = None
    context.messages = []
    context.form = {}


def after_scenario(context, scenario):
    pass
'''

COMMON_STEPS_PY = '''"""Reusable step definitions for generated .feature files.
Wire these to your real app (Selenium, Playwright, API client, etc.)."""

from behave import given, when, then


@given("I am on the login page")
def step_on_login_page(context):
    context.current_page = "login"


@given('I have successfully logged in as "{email}"')
def step_logged_in(context, email):
    context.current_page = "dashboard"
    context.user_email = email


@when('I navigate to the "{page}" page')
def step_navigate(context, page):
    context.current_page = page.lower().replace(" ", "_")


@given('I have a registered account with email "{email}" and password "{password}"')
def step_registered_account(context, email, password):
    context.accounts = getattr(context, "accounts", {})
    context.accounts[email] = password


@given('I have a registered account with email "{email}"')
def step_registered_email(context, email):
    context.accounts = getattr(context, "accounts", {})
    context.accounts.setdefault(email, "password")


@when('I enter "{value}" into the email field')
def step_enter_email(context, value):
    context.form["email"] = value


@when('I enter "{value}" into the password field')
def step_enter_password(context, value):
    context.form["password"] = value


@when('I leave the email field empty')
def step_empty_email(context):
    context.form["email"] = ""


@when('I leave the password field empty')
def step_empty_password(context):
    context.form["password"] = ""


@when('I click the "{button}" button')
def step_click_button(context, button):
    context.last_action = f"clicked_{button.lower()}"


@when('I select the "{option}" checkbox')
def step_select_checkbox(context, option):
    context.form[option.lower().replace(" ", "_")] = True


@then('I should be redirected to the account dashboard')
@then('I should be redirected to the "{page}" page')
def step_redirected(context, page="dashboard"):
    assert context.current_page in (page.lower(), "dashboard"), f"Expected {page}, got {context.current_page}"


@then('I should remain on the login page')
def step_remain_login(context):
    assert context.current_page == "login"


@then('I should see an error message "{message}"')
def step_see_error(context, message):
    context.messages.append(message)


@then('I should see a welcome message "{message}"')
def step_see_welcome(context, message):
    context.messages.append(message)


@then('I should see a welcome message containing my username')
def step_welcome_username(context):
    pass


@then('my login session should be remembered for future visits')
def step_remember_session(context):
    context.session_remembered = True


@then('my user session should be active')
def step_session_active(context):
    assert context.current_page != "login"


@then('I should be able to view the content of the "{page}" page')
def step_view_page(context, page):
    assert context.current_page == page.lower().replace(" ", "_")


@then('I should see a validation error message for the email field "{message}"')
def step_email_validation(context, message):
    context.messages.append(f"email: {message}")


@then('I should see a validation error message for the password field "{message}"')
def step_password_validation(context, message):
    context.messages.append(f"password: {message}")
'''

README_BEHAVE = """# Behave Test Package

Generated by **Test Case Generator** — ready to run with [Behave](https://behave.readthedocs.io/) (Python BDD).

## Quick start

```powershell
python -m venv venv
.\\venv\\Scripts\\activate
pip install behave
behave
```

Run by tag:

```powershell
behave --tags=@positive
behave --tags=@negative
behave --tags=@edge
```

Dry-run (list steps without executing):

```powershell
behave --dry-run
```

## Project layout

```
features/
  *.feature          <- generated Gherkin scenarios
  environment.py     <- setup/teardown hooks
  steps/
    common_steps.py  <- step definitions (wire to your app)
behave.ini
```

## Wire to your application

Edit `features/steps/common_steps.py` and replace stub assertions with real checks.
"""

README_CUCUMBER = """# Cucumber Setup (Java / JavaScript)

Copy the `.feature` file into your Cucumber project.

## Cucumber-JVM (Java)

1. Copy `*.feature` -> `src/test/resources/features/`
2. Add `cucumber-java`, `cucumber-junit` dependencies
3. Create step definition classes matching Given/When/Then text
4. Run: `mvn test`

## Cucumber-JS (Node)

1. Copy `*.feature` -> `features/`
2. `npm install @cucumber/cucumber`
3. Create `features/step_definitions/steps.js`
4. Run: `npx cucumber-js`

## Tags

Filter with: `cucumber --tags "@positive"`
"""
