import re


def format_for_cucumber_behave(gherkin: str, feature_name: str = "") -> str:
    """Normalize LLM output into Cucumber/Behave-compatible Gherkin."""
    text = gherkin.strip()

    fence_match = re.search(r"```(?:gherkin|feature)?\s*\n?(.*?)\n?```", text, re.DOTALL | re.IGNORECASE)
    if fence_match:
        text = fence_match.group(1).strip()

    lines = text.splitlines()
    formatted: list[str] = []

    header = [
        "# Generated by Test Case Generator",
        "# Ready for: Cucumber (Java/JavaScript) | Behave (Python)",
        "# Docs: https://cucumber.io/docs/gherkin/ | https://behave.readthedocs.io/",
        "",
    ]
    formatted.extend(header)

    for line in lines:
        stripped = line.strip()
        if not stripped:
            formatted.append("")
            continue

        if stripped.startswith("Feature:"):
            formatted.append(stripped)
        elif stripped.startswith(("@", "Scenario:", "Scenario Outline:", "Examples:", "Background:")):
            formatted.append(f"  {stripped}")
        elif stripped.startswith(("Given ", "When ", "Then ", "And ", "But ", "|")):
            formatted.append(f"    {stripped}")
        elif line.startswith("  ") and not line.startswith("    "):
            formatted.append(line)
        else:
            formatted.append(f"  {stripped}")

    if feature_name and not any(l.startswith("Feature:") for l in formatted):
        formatted.insert(len(header), f"Feature: {feature_name}")

    result = "\n".join(formatted).strip() + "\n"
    _validate_gherkin(result)
    return result


def _validate_gherkin(gherkin: str) -> None:
    if not re.search(r"^Feature:\s+.+", gherkin, re.MULTILINE):
        raise ValueError("Invalid Gherkin: missing Feature line")

    scenarios = re.findall(r"^\s*Scenario(?: Outline)?:", gherkin, re.MULTILINE)
    if not scenarios:
        raise ValueError("Invalid Gherkin: no Scenario blocks found")

    steps = re.findall(r"^\s*(Given|When|Then|And|But)\s+", gherkin, re.MULTILINE)
    if not steps:
        raise ValueError("Invalid Gherkin: no Given/When/Then steps found")
